"""Phase 5, step 1: turn the numbers Phase 3 already computed into LaTeX
macros (`report/generated_stats.tex`), so the report's prose can cite
`\\statGini` instead of a hardcoded "0.670" that silently goes stale the
next time the data (or the departments in scope) change.

Scope, by design (see docs/adding_a_department.md for the full trade-off):
this module only macro-izes numbers that are mechanically derivable from
data/outputs/*.csv and data/processed/*.parquet -- i.e. things Phase 3
recomputes every run. It deliberately does NOT try to regenerate the
report's interpretive prose (which department's average looks better and
why, which district gets named in a sentence) -- that is analysis writing,
not arithmetic, and re-deriving it for a different set of departments is a
human (or LLM-assisted) editing pass, not a pipeline step. Numbers that
came from one-off, non-reproducible measurements taken during development
(graph node counts from a specific run, the national-level cross-check
percentages) are also left as static prose for the same reason: they
describe what happened during development, not "the data" as it stands
today, so there is nothing here for them to go stale against.

Run with: python -m src.report_stats  (standalone, reads whatever is
already in data/outputs/ and data/processed/) -- or call generate() from
pipeline_phase3.run() right after it writes those files.
"""

from __future__ import annotations

import re
import unicodedata

import pandas as pd

from src.config import load_config
from src.logging_utils import get_logger

logger = get_logger("report_stats")


def _dept_key(name: str) -> str:
    """'Lambayeque' -> 'Lambayeque', 'San Martín' -> 'SanMartin' -- a LaTeX
    macro name may only contain letters, so every department name in scope
    gets a deterministic, accent-stripped, space-stripped macro suffix.
    Swapping departments means the prose has to reference a different
    suffix (e.g. \\statMeanAccessPiura instead of \\statMeanAccessCusco) --
    a find-and-replace, not a recomputation."""
    stripped = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^A-Za-z]", "", stripped.title())


def _fmt_int(n: float | int) -> str:
    """3631 -> '3{,}631', matching the thousands-grouping already used
    throughout main.tex (a literal '{,}' so babel's spanish option doesn't
    swallow a bare comma)."""
    return f"{int(round(n)):,}".replace(",", "{,}")


def _fmt(x: float, decimals: int = 1) -> str:
    return f"{x:.{decimals}f}"


def _macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


_ORDINAL_WORDS = ["Zeroth", "First", "Second", "Third", "Fourth", "Fifth", "Sixth", "Seventh", "Eighth", "Ninth", "Tenth"]


def _ordinal(n: int) -> str:
    """LaTeX control-word names may only contain letters -- no digits -- so
    a numbered macro (the 3rd-worst district, the 2nd coverage band) needs
    its index spelled out ('Third', not '3'). Raises rather than falling
    back to a digit-bearing name (which would silently produce an invalid
    \\newcommand) -- config.md would need >10 coverage bands to hit this."""
    if not (0 <= n < len(_ORDINAL_WORDS)):
        raise ValueError(f"_ordinal({n}): no word form defined (extend _ORDINAL_WORDS)")
    return _ORDINAL_WORDS[n]


_ES_LOWERCASE_WORDS = {"y", "de", "del", "la", "las", "el", "los"}


def _title_es(s: str) -> str:
    """RENIPRESS/SIGMED names are all-caps in the raw data ('CALIDAD Y
    SALUD'). str.title() alone gives 'Calidad Y Salud'; keep short Spanish
    connector words lowercase, matching how a person would actually write
    the name in prose."""
    words = str(s).title().split()
    return " ".join(w if w.lower() not in _ES_LOWERCASE_WORDS else w.lower() for w in words)


def generate() -> None:
    cfg = load_config()
    out_dir = cfg.path("outputs_dir")
    report_dir = cfg.path("report_dir")

    lines: list[str] = [
        "% AUTO-GENERATED by src/report_stats.py -- do not edit by hand.\n",
        "% Regenerate with `python -m src.report_stats` (or `python -m src.pipeline_phase3`,\n",
        "% which calls it automatically) after any change to the data or to config.md.\n\n",
    ]

    departments = cfg.department_names
    dept_and = " y ".join([", ".join(departments[:-1]), departments[-1]]) if len(departments) > 1 else departments[0]
    lines.append(_macro("statNDepartments", str(len(departments))))
    lines.append(_macro("statDeptList", dept_and))

    # --- config.md constants (methodology description, not measurement --
    # macro-ized too, since editing config.md's thresholds/speeds should
    # update the report's description of them without a manual text edit) --
    bands = cfg.metrics["coverage_bands_minutes"]
    for i, edge in enumerate(bands, start=1):
        lines.append(_macro(f"statCoverageBand{_ordinal(i)}", str(int(edge))))
    lines.append(_macro("statUrbanPopThreshold", _fmt_int(cfg.metrics["urban_pop_threshold"])))
    speeds = cfg.routing["fallback_speeds_kmh"]
    lines.append(_macro("statSpeedCar", str(speeds["car"])))
    lines.append(_macro("statSpeedBike", str(speeds["bike"])))
    lines.append(_macro("statSpeedFoot", str(speeds["foot"])))
    lines.append(_macro("statSpeedRatioCarFoot", _fmt(speeds["car"] / speeds["foot"])))

    # --- counts from the processed layer ---------------------------------
    import geopandas as gpd

    facilities = gpd.read_parquet(cfg.path("processed_dir") / "renipress_clean_3depts.parquet")
    lines.append(_macro("statNFacilities", _fmt_int(len(facilities))))
    if {"department", "is_resolutive", "status_raw"}.issubset(facilities.columns):
        active = cfg.active_status_values
        resolutive = facilities[facilities["is_resolutive"] & facilities["status_raw"].isin(active)]
        per_dept_n = resolutive["department"].str.upper().value_counts()
        vals = [per_dept_n.get(d.upper(), 0) for d in departments]
        if vals:
            lines.append(_macro("statMinResolutivePerDept", _fmt_int(min(vals))))
            lines.append(_macro("statMaxResolutivePerDept", _fmt_int(max(vals))))

    demand_raw_path = cfg.path("processed_dir") / "sigmed_demand_3depts.parquet"
    if demand_raw_path.exists():
        demand_raw = gpd.read_parquet(demand_raw_path)
        lines.append(_macro("statNCentrosPoblados", _fmt_int(len(demand_raw))))

    demand_sampled = gpd.read_parquet(cfg.path("processed_dir") / "demand_points_sampled_3depts.parquet")
    lines.append(_macro("statNSampled", _fmt_int(len(demand_sampled))))
    lines.append(_macro("statMaxDemandPoints", _fmt_int(cfg.routing["max_demand_points"])))

    # --- coverage bands ----------------------------------------------------
    coverage_path = out_dir / "coverage_bands.csv"
    if coverage_path.exists():
        coverage = pd.read_csv(coverage_path)
        first_threshold = cfg.metrics["coverage_bands_minutes"][0]
        band_label = f"0-{int(first_threshold)} min"
        row = coverage[coverage["band"] == band_label]
        if not row.empty:
            lines.append(_macro("statPctUnderFirstBand", _fmt(row["share"].iloc[0] * 100)))
            lines.append(_macro("statFirstBandMinutes", str(int(first_threshold))))
        unroutable = coverage[coverage["band"] == "unroutable"]
        if not unroutable.empty:
            lines.append(_macro("statPctUnroutable", _fmt(unroutable["share"].iloc[0] * 100, 2)))

    # --- Gini ---------------------------------------------------------------
    gini_path = out_dir / "gini_coefficient.txt"
    if gini_path.exists():
        gini = float(gini_path.read_text(encoding="utf-8").strip())
        lines.append(_macro("statGini", _fmt(gini, 3)))

    # --- urban/rural contrast ------------------------------------------------
    ur_path = out_dir / "urban_rural_contrast.csv"
    if ur_path.exists():
        ur = pd.read_csv(ur_path)
        urban_row = ur[ur["is_urban"] == True]  # noqa: E712 (pandas bool column, not a real bool literal check pitfall here)
        rural_row = ur[ur["is_urban"] == False]  # noqa: E712
        if not urban_row.empty and not rural_row.empty:
            urban_mean = urban_row["population_weighted_mean_t_min"].iloc[0]
            rural_mean = rural_row["population_weighted_mean_t_min"].iloc[0]
            lines.append(_macro("statUrbanMean", _fmt(urban_mean)))
            lines.append(_macro("statRuralMean", _fmt(rural_mean)))
            lines.append(_macro("statUrbanRuralRatio", _fmt(rural_mean / urban_mean)))

    # --- per-department access mean -----------------------------------------
    dept_access_path = out_dir / "access_by_department.csv"
    dept_means: dict[str, float] = {}
    if dept_access_path.exists():
        dept_access = pd.read_csv(dept_access_path)
        for _, row in dept_access.iterrows():
            name = _title_es(row["department"])
            dept_means[name] = row["population_weighted_mean_t_min"]
            key = _dept_key(name)
            lines.append(_macro(f"statMeanAccess{key}", _fmt(row["population_weighted_mean_t_min"])))
            lines.append(_macro(f"statPctUnroutable{key}", _fmt(row["pct_population_unroutable"], 2)))
        if dept_means:
            best_name = min(dept_means, key=dept_means.get)
            worst_avg_name = max(dept_means, key=dept_means.get)
            lines.append(_macro("statBestAvgDept", best_name))
            lines.append(_macro("statWorstAvgDept", worst_avg_name))

    # --- critical gap ranking (worst district) ------------------------------
    gaps_path = out_dir / "critical_gap_ranking.csv"
    districts_path = cfg.path("processed_dir") / "districts_3depts.parquet"
    if gaps_path.exists() and districts_path.exists():
        gaps = pd.read_csv(gaps_path, dtype={"ubigeo": str})
        districts = gpd.read_parquet(districts_path)
        name_by_ubigeo = dict(zip(districts["IDDIST"].astype(str), districts["NOMBDIST"]))
        gaps["district_name"] = gaps["ubigeo"].str.zfill(6).map(name_by_ubigeo)

        worst = gaps.iloc[0]
        lines.append(_macro("statWorstDistrictName", _title_es(worst["district_name"])))
        lines.append(_macro("statWorstDistrictDept", _title_es(worst["department"])))
        lines.append(_macro("statWorstDistrictMean", _fmt(worst["population_weighted_mean_t_min"])))

        top_n = min(5, len(gaps))
        top = gaps.head(top_n)
        mode_dept = top["department"].mode().iloc[0]
        mode_count = int((top["department"] == mode_dept).sum())
        lines.append(_macro("statTopGapsN", str(top_n)))
        lines.append(_macro("statTopGapsDeptMode", _title_es(mode_dept)))
        lines.append(_macro("statTopGapsDeptModeCount", str(mode_count)))

        # The 3 worst districts overall (not just within the top-N) that
        # belong to the department dominating the top-N ranking -- lets the
        # prose name specific districts+times without hand-picking rows.
        mode_dept_rows = gaps[gaps["department"] == mode_dept].head(3).reset_index(drop=True)
        for i, mrow in mode_dept_rows.iterrows():
            lines.append(_macro(f"statTopGapsMode{_ordinal(i + 1)}Dist", _title_es(mrow["district_name"])))
            lines.append(_macro(f"statTopGapsMode{_ordinal(i + 1)}Time", _fmt(mrow["population_weighted_mean_t_min"])))

    # --- cross-mode (car vs foot) --------------------------------------------
    cross_path = out_dir / "cross_mode_comparison.csv"
    if cross_path.exists():
        cross = pd.read_csv(cross_path)
        both = cross.dropna(subset=["t_min_car", "t_min_foot"])
        if len(both):
            ratio = (both["t_min_foot"] / both["t_min_car"]).median()
            lines.append(_macro("statWalkCarRatio", _fmt(ratio)))
            lines.append(_macro("statNBothRoutable", _fmt_int(len(both))))
            lines.append(_macro("statPctBothRoutable", _fmt(100 * len(both) / len(cross), 2)))
            for dept in departments:
                sub = both[both["department"].str.upper() == dept.upper()]
                if len(sub):
                    key = _dept_key(dept)
                    lines.append(_macro(f"statWalkCarRatio{key}", _fmt((sub["t_min_foot"] / sub["t_min_car"]).median())))

    # --- straight-line vs. network detour -----------------------------------
    straight_path = out_dir / "straight_line_vs_network.csv"
    if straight_path.exists() and len(pd.read_csv(straight_path)):
        straight = pd.read_csv(straight_path)
        straight = straight.merge(
            demand_sampled[["department"]].reset_index().rename(columns={"index": "demand_id"}),
            on="demand_id", how="left",
        )
        detour_by_dept: dict[str, float] = {}
        for dept in departments:
            sub = straight[straight["department"].str.upper() == dept.upper()]
            if len(sub):
                detour_by_dept[dept] = sub["detour_factor"].median()
                key = _dept_key(dept)
                lines.append(_macro(f"statDetour{key}", _fmt(detour_by_dept[dept], 2)))

        # If the scope includes one coastal and one andean department, the
        # relative-detour-cost sentence in the Discussion section can cite a
        # live percentage instead of a hand-computed one; silently skipped
        # otherwise (e.g. a scope with two coastal departments).
        by_region = {d.region_type: d.name for d in cfg.departments}
        coastal, andean = by_region.get("coastal"), by_region.get("andean")
        if coastal in detour_by_dept and andean in detour_by_dept and detour_by_dept[coastal]:
            diff_pct = 100 * (detour_by_dept[andean] - detour_by_dept[coastal]) / detour_by_dept[coastal]
            lines.append(_macro("statDetourAndeanVsCoastalPct", _fmt(diff_pct, 0)))

    # --- facility siting (innovation) ---------------------------------------
    siting_path = out_dir / "facility_siting_recommendations.csv"
    if siting_path.exists() and len(pd.read_csv(siting_path)):
        siting = pd.read_csv(siting_path)
        for dept in departments:
            sub = siting[siting["department"].str.upper() == dept.upper()].sort_values("rank")
            if sub.empty:
                continue
            key = _dept_key(dept)
            top = sub.iloc[0]
            lines.append(_macro(f"statSitingTopName{key}", _title_es(top["facility_name"])))
            lines.append(_macro(f"statSitingTopDistrict{key}", _title_es(top["district"])))
            lines.append(_macro(f"statSitingTopGain{key}", _fmt_int(top["marginal_population_gained"])))
            rest_gain = sub.iloc[1:]["marginal_population_gained"].sum()
            lines.append(_macro(f"statSitingRestGain{key}", _fmt_int(rest_gain)))
            if rest_gain > 0:
                # NOT the same thing as "casi tanto como" (roughly equal to) --
                # a previous hand-written draft claimed that, but the top
                # pick is usually well above the other picks combined, not
                # merely comparable to them. Report the ratio, not a fixed
                # form of words, so the sentence stays accurate regardless
                # of which department/facilities this ends up describing.
                lines.append(_macro(f"statSitingTopVsRestRatio{key}", _fmt(top["marginal_population_gained"] / rest_gain, 1)))

    # --- Phase 1 data-quality figures (3-department scope only) ------------
    dq_path = out_dir / "data_quality_report.csv"
    if dq_path.exists():
        dq = pd.read_csv(dq_path)
        renipress = dq[dq["source"] == "renipress"]

        def _pct_flagged(rule: str) -> float | None:
            row = renipress[renipress["rule"] == rule]
            return float(row["pct_flagged"].iloc[0]) if not row.empty and pd.notna(row["pct_flagged"].iloc[0]) else None

        missing_coords = _pct_flagged("missing_or_zero_coordinates")
        if missing_coords is not None:
            lines.append(_macro("statPctMissingCoords", _fmt(missing_coords)))
        cat0 = _pct_flagged("unclassified_category")
        if cat0 is not None:
            lines.append(_macro("statPctCategoryZero", _fmt(cat0)))

        for src_name, macro_suffix in (("renipress", "Renipress"), ("sigmed", "Sigmed")):
            row = dq[(dq["source"] == src_name) & (dq["rule"] == "district_containment")]
            if not row.empty and pd.notna(row["n_checkable"].iloc[0]) and row["n_checkable"].iloc[0] > 0:
                pct = 100 * row["n_flagged"].iloc[0] / row["n_checkable"].iloc[0]
                lines.append(_macro(f"statPctContainment{macro_suffix}", _fmt(pct)))

    stats_path = report_dir / "generated_stats.tex"
    stats_path.write_text("".join(lines), encoding="utf-8")
    logger.info("Escritas %d macros en %s", len(lines) - 3, stats_path)


if __name__ == "__main__":
    generate()
